/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedirectKakaoRouteRouteImport } from './routes/redirect-kakao/route'
import { Route as MainLayoutRouteRouteImport } from './routes/_mainLayout/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MainLayoutRegisterRouteRouteImport } from './routes/_mainLayout/register/route'
import { Route as MainLayoutRankingsRouteRouteImport } from './routes/_mainLayout/rankings/route'
import { Route as MainLayoutMyRouteRouteImport } from './routes/_mainLayout/my/route'
import { Route as MainLayoutLoginRouteRouteImport } from './routes/_mainLayout/login/route'
import { Route as MainLayoutAboutRouteRouteImport } from './routes/_mainLayout/about/route'
import { Route as MainLayoutTestPapersIndexRouteImport } from './routes/_mainLayout/test-papers/index'
import { Route as MainLayoutSettingIndexRouteImport } from './routes/_mainLayout/setting/index'
import { Route as MainLayoutProblemsIndexRouteImport } from './routes/_mainLayout/problems/index'
import { Route as MainLayoutContestsIndexRouteImport } from './routes/_mainLayout/contests/index'
import { Route as MainLayoutTestPapersTestPaperIdRouteImport } from './routes/_mainLayout/test-papers/$testPaperId'
import { Route as MainLayoutProblemsProblemIdRouteImport } from './routes/_mainLayout/problems/$problemId'
import { Route as MainLayoutContestsContestIdRouteImport } from './routes/_mainLayout/contests/$contestId'
import { Route as MainLayoutProblemsUlsanRouteRouteImport } from './routes/_mainLayout/problems/ulsan/route'
import { Route as MainLayoutProblemsSeoulRouteRouteImport } from './routes/_mainLayout/problems/seoul/route'
import { Route as MainLayoutProblemsSchoolRouteRouteImport } from './routes/_mainLayout/problems/school/route'
import { Route as MainLayoutProblemsPopularRouteRouteImport } from './routes/_mainLayout/problems/popular/route'
import { Route as MainLayoutProblemsNewRouteRouteImport } from './routes/_mainLayout/problems/new/route'
import { Route as MainLayoutProblemsIncheonRouteRouteImport } from './routes/_mainLayout/problems/incheon/route'
import { Route as MainLayoutProblemsGwangjuRouteRouteImport } from './routes/_mainLayout/problems/gwangju/route'
import { Route as MainLayoutProblemsDaejeonRouteRouteImport } from './routes/_mainLayout/problems/daejeon/route'
import { Route as MainLayoutProblemsDaeguRouteRouteImport } from './routes/_mainLayout/problems/daegu/route'
import { Route as MainLayoutProblemsCourseRouteRouteImport } from './routes/_mainLayout/problems/course/route'
import { Route as MainLayoutProblemsBusanRouteRouteImport } from './routes/_mainLayout/problems/busan/route'
import { Route as MainLayoutBoardWriteQuestionRouteRouteImport } from './routes/_mainLayout/board/write/question/route'
import { Route as MainLayoutBoardListNoticeRouteRouteImport } from './routes/_mainLayout/board/list/notice/route'
import { Route as MainLayoutBoardListFreeRouteRouteImport } from './routes/_mainLayout/board/list/free/route'
import { Route as MainLayoutBoardListAllRouteRouteImport } from './routes/_mainLayout/board/list/all/route'
import { Route as MainLayoutBoardQuestionSubjectTitleRouteRouteImport } from './routes/_mainLayout/board/question/subject/$title/route'
import { Route as MainLayoutBoardQuestionProblemProjectIdRouteRouteImport } from './routes/_mainLayout/board/question/problem/$projectId/route'
import { Route as MainLayoutBoardQuestionContestContestIdRouteRouteImport } from './routes/_mainLayout/board/question/contest/$contestId/route'

const RedirectKakaoRouteRoute = RedirectKakaoRouteRouteImport.update({
  id: '/redirect-kakao',
  path: '/redirect-kakao',
  getParentRoute: () => rootRouteImport,
} as any)
const MainLayoutRouteRoute = MainLayoutRouteRouteImport.update({
  id: '/_mainLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainLayoutRegisterRouteRoute = MainLayoutRegisterRouteRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => MainLayoutRouteRoute,
} as any)
const MainLayoutRankingsRouteRoute = MainLayoutRankingsRouteRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => MainLayoutRouteRoute,
} as any)
const MainLayoutMyRouteRoute = MainLayoutMyRouteRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => MainLayoutRouteRoute,
} as any)
const MainLayoutLoginRouteRoute = MainLayoutLoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => MainLayoutRouteRoute,
} as any)
const MainLayoutAboutRouteRoute = MainLayoutAboutRouteRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MainLayoutRouteRoute,
} as any)
const MainLayoutTestPapersIndexRoute =
  MainLayoutTestPapersIndexRouteImport.update({
    id: '/test-papers/',
    path: '/test-papers/',
    getParentRoute: () => MainLayoutRouteRoute,
  } as any)
const MainLayoutSettingIndexRoute = MainLayoutSettingIndexRouteImport.update({
  id: '/setting/',
  path: '/setting/',
  getParentRoute: () => MainLayoutRouteRoute,
} as any)
const MainLayoutProblemsIndexRoute = MainLayoutProblemsIndexRouteImport.update({
  id: '/problems/',
  path: '/problems/',
  getParentRoute: () => MainLayoutRouteRoute,
} as any)
const MainLayoutContestsIndexRoute = MainLayoutContestsIndexRouteImport.update({
  id: '/contests/',
  path: '/contests/',
  getParentRoute: () => MainLayoutRouteRoute,
} as any)
const MainLayoutTestPapersTestPaperIdRoute =
  MainLayoutTestPapersTestPaperIdRouteImport.update({
    id: '/test-papers/$testPaperId',
    path: '/test-papers/$testPaperId',
    getParentRoute: () => MainLayoutRouteRoute,
  } as any)
const MainLayoutProblemsProblemIdRoute =
  MainLayoutProblemsProblemIdRouteImport.update({
    id: '/problems/$problemId',
    path: '/problems/$problemId',
    getParentRoute: () => MainLayoutRouteRoute,
  } as any)
const MainLayoutContestsContestIdRoute =
  MainLayoutContestsContestIdRouteImport.update({
    id: '/contests/$contestId',
    path: '/contests/$contestId',
    getParentRoute: () => MainLayoutRouteRoute,
  } as any)
const MainLayoutProblemsUlsanRouteRoute =
  MainLayoutProblemsUlsanRouteRouteImport.update({
    id: '/problems/ulsan',
    path: '/problems/ulsan',
    getParentRoute: () => MainLayoutRouteRoute,
  } as any)
const MainLayoutProblemsSeoulRouteRoute =
  MainLayoutProblemsSeoulRouteRouteImport.update({
    id: '/problems/seoul',
    path: '/problems/seoul',
    getParentRoute: () => MainLayoutRouteRoute,
  } as any)
const MainLayoutProblemsSchoolRouteRoute =
  MainLayoutProblemsSchoolRouteRouteImport.update({
    id: '/problems/school',
    path: '/problems/school',
    getParentRoute: () => MainLayoutRouteRoute,
  } as any)
const MainLayoutProblemsPopularRouteRoute =
  MainLayoutProblemsPopularRouteRouteImport.update({
    id: '/problems/popular',
    path: '/problems/popular',
    getParentRoute: () => MainLayoutRouteRoute,
  } as any)
const MainLayoutProblemsNewRouteRoute =
  MainLayoutProblemsNewRouteRouteImport.update({
    id: '/problems/new',
    path: '/problems/new',
    getParentRoute: () => MainLayoutRouteRoute,
  } as any)
const MainLayoutProblemsIncheonRouteRoute =
  MainLayoutProblemsIncheonRouteRouteImport.update({
    id: '/problems/incheon',
    path: '/problems/incheon',
    getParentRoute: () => MainLayoutRouteRoute,
  } as any)
const MainLayoutProblemsGwangjuRouteRoute =
  MainLayoutProblemsGwangjuRouteRouteImport.update({
    id: '/problems/gwangju',
    path: '/problems/gwangju',
    getParentRoute: () => MainLayoutRouteRoute,
  } as any)
const MainLayoutProblemsDaejeonRouteRoute =
  MainLayoutProblemsDaejeonRouteRouteImport.update({
    id: '/problems/daejeon',
    path: '/problems/daejeon',
    getParentRoute: () => MainLayoutRouteRoute,
  } as any)
const MainLayoutProblemsDaeguRouteRoute =
  MainLayoutProblemsDaeguRouteRouteImport.update({
    id: '/problems/daegu',
    path: '/problems/daegu',
    getParentRoute: () => MainLayoutRouteRoute,
  } as any)
const MainLayoutProblemsCourseRouteRoute =
  MainLayoutProblemsCourseRouteRouteImport.update({
    id: '/problems/course',
    path: '/problems/course',
    getParentRoute: () => MainLayoutRouteRoute,
  } as any)
const MainLayoutProblemsBusanRouteRoute =
  MainLayoutProblemsBusanRouteRouteImport.update({
    id: '/problems/busan',
    path: '/problems/busan',
    getParentRoute: () => MainLayoutRouteRoute,
  } as any)
const MainLayoutBoardWriteQuestionRouteRoute =
  MainLayoutBoardWriteQuestionRouteRouteImport.update({
    id: '/board/write/question',
    path: '/board/write/question',
    getParentRoute: () => MainLayoutRouteRoute,
  } as any)
const MainLayoutBoardListNoticeRouteRoute =
  MainLayoutBoardListNoticeRouteRouteImport.update({
    id: '/board/list/notice',
    path: '/board/list/notice',
    getParentRoute: () => MainLayoutRouteRoute,
  } as any)
const MainLayoutBoardListFreeRouteRoute =
  MainLayoutBoardListFreeRouteRouteImport.update({
    id: '/board/list/free',
    path: '/board/list/free',
    getParentRoute: () => MainLayoutRouteRoute,
  } as any)
const MainLayoutBoardListAllRouteRoute =
  MainLayoutBoardListAllRouteRouteImport.update({
    id: '/board/list/all',
    path: '/board/list/all',
    getParentRoute: () => MainLayoutRouteRoute,
  } as any)
const MainLayoutBoardQuestionSubjectTitleRouteRoute =
  MainLayoutBoardQuestionSubjectTitleRouteRouteImport.update({
    id: '/board/question/subject/$title',
    path: '/board/question/subject/$title',
    getParentRoute: () => MainLayoutRouteRoute,
  } as any)
const MainLayoutBoardQuestionProblemProjectIdRouteRoute =
  MainLayoutBoardQuestionProblemProjectIdRouteRouteImport.update({
    id: '/board/question/problem/$projectId',
    path: '/board/question/problem/$projectId',
    getParentRoute: () => MainLayoutRouteRoute,
  } as any)
const MainLayoutBoardQuestionContestContestIdRouteRoute =
  MainLayoutBoardQuestionContestContestIdRouteRouteImport.update({
    id: '/board/question/contest/$contestId',
    path: '/board/question/contest/$contestId',
    getParentRoute: () => MainLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/redirect-kakao': typeof RedirectKakaoRouteRoute
  '/about': typeof MainLayoutAboutRouteRoute
  '/login': typeof MainLayoutLoginRouteRoute
  '/my': typeof MainLayoutMyRouteRoute
  '/rankings': typeof MainLayoutRankingsRouteRoute
  '/register': typeof MainLayoutRegisterRouteRoute
  '/problems/busan': typeof MainLayoutProblemsBusanRouteRoute
  '/problems/course': typeof MainLayoutProblemsCourseRouteRoute
  '/problems/daegu': typeof MainLayoutProblemsDaeguRouteRoute
  '/problems/daejeon': typeof MainLayoutProblemsDaejeonRouteRoute
  '/problems/gwangju': typeof MainLayoutProblemsGwangjuRouteRoute
  '/problems/incheon': typeof MainLayoutProblemsIncheonRouteRoute
  '/problems/new': typeof MainLayoutProblemsNewRouteRoute
  '/problems/popular': typeof MainLayoutProblemsPopularRouteRoute
  '/problems/school': typeof MainLayoutProblemsSchoolRouteRoute
  '/problems/seoul': typeof MainLayoutProblemsSeoulRouteRoute
  '/problems/ulsan': typeof MainLayoutProblemsUlsanRouteRoute
  '/contests/$contestId': typeof MainLayoutContestsContestIdRoute
  '/problems/$problemId': typeof MainLayoutProblemsProblemIdRoute
  '/test-papers/$testPaperId': typeof MainLayoutTestPapersTestPaperIdRoute
  '/contests': typeof MainLayoutContestsIndexRoute
  '/problems': typeof MainLayoutProblemsIndexRoute
  '/setting': typeof MainLayoutSettingIndexRoute
  '/test-papers': typeof MainLayoutTestPapersIndexRoute
  '/board/list/all': typeof MainLayoutBoardListAllRouteRoute
  '/board/list/free': typeof MainLayoutBoardListFreeRouteRoute
  '/board/list/notice': typeof MainLayoutBoardListNoticeRouteRoute
  '/board/write/question': typeof MainLayoutBoardWriteQuestionRouteRoute
  '/board/question/contest/$contestId': typeof MainLayoutBoardQuestionContestContestIdRouteRoute
  '/board/question/problem/$projectId': typeof MainLayoutBoardQuestionProblemProjectIdRouteRoute
  '/board/question/subject/$title': typeof MainLayoutBoardQuestionSubjectTitleRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/redirect-kakao': typeof RedirectKakaoRouteRoute
  '/about': typeof MainLayoutAboutRouteRoute
  '/login': typeof MainLayoutLoginRouteRoute
  '/my': typeof MainLayoutMyRouteRoute
  '/rankings': typeof MainLayoutRankingsRouteRoute
  '/register': typeof MainLayoutRegisterRouteRoute
  '/problems/busan': typeof MainLayoutProblemsBusanRouteRoute
  '/problems/course': typeof MainLayoutProblemsCourseRouteRoute
  '/problems/daegu': typeof MainLayoutProblemsDaeguRouteRoute
  '/problems/daejeon': typeof MainLayoutProblemsDaejeonRouteRoute
  '/problems/gwangju': typeof MainLayoutProblemsGwangjuRouteRoute
  '/problems/incheon': typeof MainLayoutProblemsIncheonRouteRoute
  '/problems/new': typeof MainLayoutProblemsNewRouteRoute
  '/problems/popular': typeof MainLayoutProblemsPopularRouteRoute
  '/problems/school': typeof MainLayoutProblemsSchoolRouteRoute
  '/problems/seoul': typeof MainLayoutProblemsSeoulRouteRoute
  '/problems/ulsan': typeof MainLayoutProblemsUlsanRouteRoute
  '/contests/$contestId': typeof MainLayoutContestsContestIdRoute
  '/problems/$problemId': typeof MainLayoutProblemsProblemIdRoute
  '/test-papers/$testPaperId': typeof MainLayoutTestPapersTestPaperIdRoute
  '/contests': typeof MainLayoutContestsIndexRoute
  '/problems': typeof MainLayoutProblemsIndexRoute
  '/setting': typeof MainLayoutSettingIndexRoute
  '/test-papers': typeof MainLayoutTestPapersIndexRoute
  '/board/list/all': typeof MainLayoutBoardListAllRouteRoute
  '/board/list/free': typeof MainLayoutBoardListFreeRouteRoute
  '/board/list/notice': typeof MainLayoutBoardListNoticeRouteRoute
  '/board/write/question': typeof MainLayoutBoardWriteQuestionRouteRoute
  '/board/question/contest/$contestId': typeof MainLayoutBoardQuestionContestContestIdRouteRoute
  '/board/question/problem/$projectId': typeof MainLayoutBoardQuestionProblemProjectIdRouteRoute
  '/board/question/subject/$title': typeof MainLayoutBoardQuestionSubjectTitleRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_mainLayout': typeof MainLayoutRouteRouteWithChildren
  '/redirect-kakao': typeof RedirectKakaoRouteRoute
  '/_mainLayout/about': typeof MainLayoutAboutRouteRoute
  '/_mainLayout/login': typeof MainLayoutLoginRouteRoute
  '/_mainLayout/my': typeof MainLayoutMyRouteRoute
  '/_mainLayout/rankings': typeof MainLayoutRankingsRouteRoute
  '/_mainLayout/register': typeof MainLayoutRegisterRouteRoute
  '/_mainLayout/problems/busan': typeof MainLayoutProblemsBusanRouteRoute
  '/_mainLayout/problems/course': typeof MainLayoutProblemsCourseRouteRoute
  '/_mainLayout/problems/daegu': typeof MainLayoutProblemsDaeguRouteRoute
  '/_mainLayout/problems/daejeon': typeof MainLayoutProblemsDaejeonRouteRoute
  '/_mainLayout/problems/gwangju': typeof MainLayoutProblemsGwangjuRouteRoute
  '/_mainLayout/problems/incheon': typeof MainLayoutProblemsIncheonRouteRoute
  '/_mainLayout/problems/new': typeof MainLayoutProblemsNewRouteRoute
  '/_mainLayout/problems/popular': typeof MainLayoutProblemsPopularRouteRoute
  '/_mainLayout/problems/school': typeof MainLayoutProblemsSchoolRouteRoute
  '/_mainLayout/problems/seoul': typeof MainLayoutProblemsSeoulRouteRoute
  '/_mainLayout/problems/ulsan': typeof MainLayoutProblemsUlsanRouteRoute
  '/_mainLayout/contests/$contestId': typeof MainLayoutContestsContestIdRoute
  '/_mainLayout/problems/$problemId': typeof MainLayoutProblemsProblemIdRoute
  '/_mainLayout/test-papers/$testPaperId': typeof MainLayoutTestPapersTestPaperIdRoute
  '/_mainLayout/contests/': typeof MainLayoutContestsIndexRoute
  '/_mainLayout/problems/': typeof MainLayoutProblemsIndexRoute
  '/_mainLayout/setting/': typeof MainLayoutSettingIndexRoute
  '/_mainLayout/test-papers/': typeof MainLayoutTestPapersIndexRoute
  '/_mainLayout/board/list/all': typeof MainLayoutBoardListAllRouteRoute
  '/_mainLayout/board/list/free': typeof MainLayoutBoardListFreeRouteRoute
  '/_mainLayout/board/list/notice': typeof MainLayoutBoardListNoticeRouteRoute
  '/_mainLayout/board/write/question': typeof MainLayoutBoardWriteQuestionRouteRoute
  '/_mainLayout/board/question/contest/$contestId': typeof MainLayoutBoardQuestionContestContestIdRouteRoute
  '/_mainLayout/board/question/problem/$projectId': typeof MainLayoutBoardQuestionProblemProjectIdRouteRoute
  '/_mainLayout/board/question/subject/$title': typeof MainLayoutBoardQuestionSubjectTitleRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/redirect-kakao'
    | '/about'
    | '/login'
    | '/my'
    | '/rankings'
    | '/register'
    | '/problems/busan'
    | '/problems/course'
    | '/problems/daegu'
    | '/problems/daejeon'
    | '/problems/gwangju'
    | '/problems/incheon'
    | '/problems/new'
    | '/problems/popular'
    | '/problems/school'
    | '/problems/seoul'
    | '/problems/ulsan'
    | '/contests/$contestId'
    | '/problems/$problemId'
    | '/test-papers/$testPaperId'
    | '/contests'
    | '/problems'
    | '/setting'
    | '/test-papers'
    | '/board/list/all'
    | '/board/list/free'
    | '/board/list/notice'
    | '/board/write/question'
    | '/board/question/contest/$contestId'
    | '/board/question/problem/$projectId'
    | '/board/question/subject/$title'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/redirect-kakao'
    | '/about'
    | '/login'
    | '/my'
    | '/rankings'
    | '/register'
    | '/problems/busan'
    | '/problems/course'
    | '/problems/daegu'
    | '/problems/daejeon'
    | '/problems/gwangju'
    | '/problems/incheon'
    | '/problems/new'
    | '/problems/popular'
    | '/problems/school'
    | '/problems/seoul'
    | '/problems/ulsan'
    | '/contests/$contestId'
    | '/problems/$problemId'
    | '/test-papers/$testPaperId'
    | '/contests'
    | '/problems'
    | '/setting'
    | '/test-papers'
    | '/board/list/all'
    | '/board/list/free'
    | '/board/list/notice'
    | '/board/write/question'
    | '/board/question/contest/$contestId'
    | '/board/question/problem/$projectId'
    | '/board/question/subject/$title'
  id:
    | '__root__'
    | '/'
    | '/_mainLayout'
    | '/redirect-kakao'
    | '/_mainLayout/about'
    | '/_mainLayout/login'
    | '/_mainLayout/my'
    | '/_mainLayout/rankings'
    | '/_mainLayout/register'
    | '/_mainLayout/problems/busan'
    | '/_mainLayout/problems/course'
    | '/_mainLayout/problems/daegu'
    | '/_mainLayout/problems/daejeon'
    | '/_mainLayout/problems/gwangju'
    | '/_mainLayout/problems/incheon'
    | '/_mainLayout/problems/new'
    | '/_mainLayout/problems/popular'
    | '/_mainLayout/problems/school'
    | '/_mainLayout/problems/seoul'
    | '/_mainLayout/problems/ulsan'
    | '/_mainLayout/contests/$contestId'
    | '/_mainLayout/problems/$problemId'
    | '/_mainLayout/test-papers/$testPaperId'
    | '/_mainLayout/contests/'
    | '/_mainLayout/problems/'
    | '/_mainLayout/setting/'
    | '/_mainLayout/test-papers/'
    | '/_mainLayout/board/list/all'
    | '/_mainLayout/board/list/free'
    | '/_mainLayout/board/list/notice'
    | '/_mainLayout/board/write/question'
    | '/_mainLayout/board/question/contest/$contestId'
    | '/_mainLayout/board/question/problem/$projectId'
    | '/_mainLayout/board/question/subject/$title'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainLayoutRouteRoute: typeof MainLayoutRouteRouteWithChildren
  RedirectKakaoRouteRoute: typeof RedirectKakaoRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/redirect-kakao': {
      id: '/redirect-kakao'
      path: '/redirect-kakao'
      fullPath: '/redirect-kakao'
      preLoaderRoute: typeof RedirectKakaoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_mainLayout': {
      id: '/_mainLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_mainLayout/register': {
      id: '/_mainLayout/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof MainLayoutRegisterRouteRouteImport
      parentRoute: typeof MainLayoutRouteRoute
    }
    '/_mainLayout/rankings': {
      id: '/_mainLayout/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof MainLayoutRankingsRouteRouteImport
      parentRoute: typeof MainLayoutRouteRoute
    }
    '/_mainLayout/my': {
      id: '/_mainLayout/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof MainLayoutMyRouteRouteImport
      parentRoute: typeof MainLayoutRouteRoute
    }
    '/_mainLayout/login': {
      id: '/_mainLayout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof MainLayoutLoginRouteRouteImport
      parentRoute: typeof MainLayoutRouteRoute
    }
    '/_mainLayout/about': {
      id: '/_mainLayout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MainLayoutAboutRouteRouteImport
      parentRoute: typeof MainLayoutRouteRoute
    }
    '/_mainLayout/test-papers/': {
      id: '/_mainLayout/test-papers/'
      path: '/test-papers'
      fullPath: '/test-papers'
      preLoaderRoute: typeof MainLayoutTestPapersIndexRouteImport
      parentRoute: typeof MainLayoutRouteRoute
    }
    '/_mainLayout/setting/': {
      id: '/_mainLayout/setting/'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof MainLayoutSettingIndexRouteImport
      parentRoute: typeof MainLayoutRouteRoute
    }
    '/_mainLayout/problems/': {
      id: '/_mainLayout/problems/'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof MainLayoutProblemsIndexRouteImport
      parentRoute: typeof MainLayoutRouteRoute
    }
    '/_mainLayout/contests/': {
      id: '/_mainLayout/contests/'
      path: '/contests'
      fullPath: '/contests'
      preLoaderRoute: typeof MainLayoutContestsIndexRouteImport
      parentRoute: typeof MainLayoutRouteRoute
    }
    '/_mainLayout/test-papers/$testPaperId': {
      id: '/_mainLayout/test-papers/$testPaperId'
      path: '/test-papers/$testPaperId'
      fullPath: '/test-papers/$testPaperId'
      preLoaderRoute: typeof MainLayoutTestPapersTestPaperIdRouteImport
      parentRoute: typeof MainLayoutRouteRoute
    }
    '/_mainLayout/problems/$problemId': {
      id: '/_mainLayout/problems/$problemId'
      path: '/problems/$problemId'
      fullPath: '/problems/$problemId'
      preLoaderRoute: typeof MainLayoutProblemsProblemIdRouteImport
      parentRoute: typeof MainLayoutRouteRoute
    }
    '/_mainLayout/contests/$contestId': {
      id: '/_mainLayout/contests/$contestId'
      path: '/contests/$contestId'
      fullPath: '/contests/$contestId'
      preLoaderRoute: typeof MainLayoutContestsContestIdRouteImport
      parentRoute: typeof MainLayoutRouteRoute
    }
    '/_mainLayout/problems/ulsan': {
      id: '/_mainLayout/problems/ulsan'
      path: '/problems/ulsan'
      fullPath: '/problems/ulsan'
      preLoaderRoute: typeof MainLayoutProblemsUlsanRouteRouteImport
      parentRoute: typeof MainLayoutRouteRoute
    }
    '/_mainLayout/problems/seoul': {
      id: '/_mainLayout/problems/seoul'
      path: '/problems/seoul'
      fullPath: '/problems/seoul'
      preLoaderRoute: typeof MainLayoutProblemsSeoulRouteRouteImport
      parentRoute: typeof MainLayoutRouteRoute
    }
    '/_mainLayout/problems/school': {
      id: '/_mainLayout/problems/school'
      path: '/problems/school'
      fullPath: '/problems/school'
      preLoaderRoute: typeof MainLayoutProblemsSchoolRouteRouteImport
      parentRoute: typeof MainLayoutRouteRoute
    }
    '/_mainLayout/problems/popular': {
      id: '/_mainLayout/problems/popular'
      path: '/problems/popular'
      fullPath: '/problems/popular'
      preLoaderRoute: typeof MainLayoutProblemsPopularRouteRouteImport
      parentRoute: typeof MainLayoutRouteRoute
    }
    '/_mainLayout/problems/new': {
      id: '/_mainLayout/problems/new'
      path: '/problems/new'
      fullPath: '/problems/new'
      preLoaderRoute: typeof MainLayoutProblemsNewRouteRouteImport
      parentRoute: typeof MainLayoutRouteRoute
    }
    '/_mainLayout/problems/incheon': {
      id: '/_mainLayout/problems/incheon'
      path: '/problems/incheon'
      fullPath: '/problems/incheon'
      preLoaderRoute: typeof MainLayoutProblemsIncheonRouteRouteImport
      parentRoute: typeof MainLayoutRouteRoute
    }
    '/_mainLayout/problems/gwangju': {
      id: '/_mainLayout/problems/gwangju'
      path: '/problems/gwangju'
      fullPath: '/problems/gwangju'
      preLoaderRoute: typeof MainLayoutProblemsGwangjuRouteRouteImport
      parentRoute: typeof MainLayoutRouteRoute
    }
    '/_mainLayout/problems/daejeon': {
      id: '/_mainLayout/problems/daejeon'
      path: '/problems/daejeon'
      fullPath: '/problems/daejeon'
      preLoaderRoute: typeof MainLayoutProblemsDaejeonRouteRouteImport
      parentRoute: typeof MainLayoutRouteRoute
    }
    '/_mainLayout/problems/daegu': {
      id: '/_mainLayout/problems/daegu'
      path: '/problems/daegu'
      fullPath: '/problems/daegu'
      preLoaderRoute: typeof MainLayoutProblemsDaeguRouteRouteImport
      parentRoute: typeof MainLayoutRouteRoute
    }
    '/_mainLayout/problems/course': {
      id: '/_mainLayout/problems/course'
      path: '/problems/course'
      fullPath: '/problems/course'
      preLoaderRoute: typeof MainLayoutProblemsCourseRouteRouteImport
      parentRoute: typeof MainLayoutRouteRoute
    }
    '/_mainLayout/problems/busan': {
      id: '/_mainLayout/problems/busan'
      path: '/problems/busan'
      fullPath: '/problems/busan'
      preLoaderRoute: typeof MainLayoutProblemsBusanRouteRouteImport
      parentRoute: typeof MainLayoutRouteRoute
    }
    '/_mainLayout/board/write/question': {
      id: '/_mainLayout/board/write/question'
      path: '/board/write/question'
      fullPath: '/board/write/question'
      preLoaderRoute: typeof MainLayoutBoardWriteQuestionRouteRouteImport
      parentRoute: typeof MainLayoutRouteRoute
    }
    '/_mainLayout/board/list/notice': {
      id: '/_mainLayout/board/list/notice'
      path: '/board/list/notice'
      fullPath: '/board/list/notice'
      preLoaderRoute: typeof MainLayoutBoardListNoticeRouteRouteImport
      parentRoute: typeof MainLayoutRouteRoute
    }
    '/_mainLayout/board/list/free': {
      id: '/_mainLayout/board/list/free'
      path: '/board/list/free'
      fullPath: '/board/list/free'
      preLoaderRoute: typeof MainLayoutBoardListFreeRouteRouteImport
      parentRoute: typeof MainLayoutRouteRoute
    }
    '/_mainLayout/board/list/all': {
      id: '/_mainLayout/board/list/all'
      path: '/board/list/all'
      fullPath: '/board/list/all'
      preLoaderRoute: typeof MainLayoutBoardListAllRouteRouteImport
      parentRoute: typeof MainLayoutRouteRoute
    }
    '/_mainLayout/board/question/subject/$title': {
      id: '/_mainLayout/board/question/subject/$title'
      path: '/board/question/subject/$title'
      fullPath: '/board/question/subject/$title'
      preLoaderRoute: typeof MainLayoutBoardQuestionSubjectTitleRouteRouteImport
      parentRoute: typeof MainLayoutRouteRoute
    }
    '/_mainLayout/board/question/problem/$projectId': {
      id: '/_mainLayout/board/question/problem/$projectId'
      path: '/board/question/problem/$projectId'
      fullPath: '/board/question/problem/$projectId'
      preLoaderRoute: typeof MainLayoutBoardQuestionProblemProjectIdRouteRouteImport
      parentRoute: typeof MainLayoutRouteRoute
    }
    '/_mainLayout/board/question/contest/$contestId': {
      id: '/_mainLayout/board/question/contest/$contestId'
      path: '/board/question/contest/$contestId'
      fullPath: '/board/question/contest/$contestId'
      preLoaderRoute: typeof MainLayoutBoardQuestionContestContestIdRouteRouteImport
      parentRoute: typeof MainLayoutRouteRoute
    }
  }
}

interface MainLayoutRouteRouteChildren {
  MainLayoutAboutRouteRoute: typeof MainLayoutAboutRouteRoute
  MainLayoutLoginRouteRoute: typeof MainLayoutLoginRouteRoute
  MainLayoutMyRouteRoute: typeof MainLayoutMyRouteRoute
  MainLayoutRankingsRouteRoute: typeof MainLayoutRankingsRouteRoute
  MainLayoutRegisterRouteRoute: typeof MainLayoutRegisterRouteRoute
  MainLayoutProblemsBusanRouteRoute: typeof MainLayoutProblemsBusanRouteRoute
  MainLayoutProblemsCourseRouteRoute: typeof MainLayoutProblemsCourseRouteRoute
  MainLayoutProblemsDaeguRouteRoute: typeof MainLayoutProblemsDaeguRouteRoute
  MainLayoutProblemsDaejeonRouteRoute: typeof MainLayoutProblemsDaejeonRouteRoute
  MainLayoutProblemsGwangjuRouteRoute: typeof MainLayoutProblemsGwangjuRouteRoute
  MainLayoutProblemsIncheonRouteRoute: typeof MainLayoutProblemsIncheonRouteRoute
  MainLayoutProblemsNewRouteRoute: typeof MainLayoutProblemsNewRouteRoute
  MainLayoutProblemsPopularRouteRoute: typeof MainLayoutProblemsPopularRouteRoute
  MainLayoutProblemsSchoolRouteRoute: typeof MainLayoutProblemsSchoolRouteRoute
  MainLayoutProblemsSeoulRouteRoute: typeof MainLayoutProblemsSeoulRouteRoute
  MainLayoutProblemsUlsanRouteRoute: typeof MainLayoutProblemsUlsanRouteRoute
  MainLayoutContestsContestIdRoute: typeof MainLayoutContestsContestIdRoute
  MainLayoutProblemsProblemIdRoute: typeof MainLayoutProblemsProblemIdRoute
  MainLayoutTestPapersTestPaperIdRoute: typeof MainLayoutTestPapersTestPaperIdRoute
  MainLayoutContestsIndexRoute: typeof MainLayoutContestsIndexRoute
  MainLayoutProblemsIndexRoute: typeof MainLayoutProblemsIndexRoute
  MainLayoutSettingIndexRoute: typeof MainLayoutSettingIndexRoute
  MainLayoutTestPapersIndexRoute: typeof MainLayoutTestPapersIndexRoute
  MainLayoutBoardListAllRouteRoute: typeof MainLayoutBoardListAllRouteRoute
  MainLayoutBoardListFreeRouteRoute: typeof MainLayoutBoardListFreeRouteRoute
  MainLayoutBoardListNoticeRouteRoute: typeof MainLayoutBoardListNoticeRouteRoute
  MainLayoutBoardWriteQuestionRouteRoute: typeof MainLayoutBoardWriteQuestionRouteRoute
  MainLayoutBoardQuestionContestContestIdRouteRoute: typeof MainLayoutBoardQuestionContestContestIdRouteRoute
  MainLayoutBoardQuestionProblemProjectIdRouteRoute: typeof MainLayoutBoardQuestionProblemProjectIdRouteRoute
  MainLayoutBoardQuestionSubjectTitleRouteRoute: typeof MainLayoutBoardQuestionSubjectTitleRouteRoute
}

const MainLayoutRouteRouteChildren: MainLayoutRouteRouteChildren = {
  MainLayoutAboutRouteRoute: MainLayoutAboutRouteRoute,
  MainLayoutLoginRouteRoute: MainLayoutLoginRouteRoute,
  MainLayoutMyRouteRoute: MainLayoutMyRouteRoute,
  MainLayoutRankingsRouteRoute: MainLayoutRankingsRouteRoute,
  MainLayoutRegisterRouteRoute: MainLayoutRegisterRouteRoute,
  MainLayoutProblemsBusanRouteRoute: MainLayoutProblemsBusanRouteRoute,
  MainLayoutProblemsCourseRouteRoute: MainLayoutProblemsCourseRouteRoute,
  MainLayoutProblemsDaeguRouteRoute: MainLayoutProblemsDaeguRouteRoute,
  MainLayoutProblemsDaejeonRouteRoute: MainLayoutProblemsDaejeonRouteRoute,
  MainLayoutProblemsGwangjuRouteRoute: MainLayoutProblemsGwangjuRouteRoute,
  MainLayoutProblemsIncheonRouteRoute: MainLayoutProblemsIncheonRouteRoute,
  MainLayoutProblemsNewRouteRoute: MainLayoutProblemsNewRouteRoute,
  MainLayoutProblemsPopularRouteRoute: MainLayoutProblemsPopularRouteRoute,
  MainLayoutProblemsSchoolRouteRoute: MainLayoutProblemsSchoolRouteRoute,
  MainLayoutProblemsSeoulRouteRoute: MainLayoutProblemsSeoulRouteRoute,
  MainLayoutProblemsUlsanRouteRoute: MainLayoutProblemsUlsanRouteRoute,
  MainLayoutContestsContestIdRoute: MainLayoutContestsContestIdRoute,
  MainLayoutProblemsProblemIdRoute: MainLayoutProblemsProblemIdRoute,
  MainLayoutTestPapersTestPaperIdRoute: MainLayoutTestPapersTestPaperIdRoute,
  MainLayoutContestsIndexRoute: MainLayoutContestsIndexRoute,
  MainLayoutProblemsIndexRoute: MainLayoutProblemsIndexRoute,
  MainLayoutSettingIndexRoute: MainLayoutSettingIndexRoute,
  MainLayoutTestPapersIndexRoute: MainLayoutTestPapersIndexRoute,
  MainLayoutBoardListAllRouteRoute: MainLayoutBoardListAllRouteRoute,
  MainLayoutBoardListFreeRouteRoute: MainLayoutBoardListFreeRouteRoute,
  MainLayoutBoardListNoticeRouteRoute: MainLayoutBoardListNoticeRouteRoute,
  MainLayoutBoardWriteQuestionRouteRoute:
    MainLayoutBoardWriteQuestionRouteRoute,
  MainLayoutBoardQuestionContestContestIdRouteRoute:
    MainLayoutBoardQuestionContestContestIdRouteRoute,
  MainLayoutBoardQuestionProblemProjectIdRouteRoute:
    MainLayoutBoardQuestionProblemProjectIdRouteRoute,
  MainLayoutBoardQuestionSubjectTitleRouteRoute:
    MainLayoutBoardQuestionSubjectTitleRouteRoute,
}

const MainLayoutRouteRouteWithChildren = MainLayoutRouteRoute._addFileChildren(
  MainLayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainLayoutRouteRoute: MainLayoutRouteRouteWithChildren,
  RedirectKakaoRouteRoute: RedirectKakaoRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
